name: Release

on:
  push:
    branches:
    - release/*

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - name: Test
      run: dotnet test MonkeyDotNet
  
  build:
    needs: test
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - name: Build
      run: dotnet build MonkeyDotNet/Monkey
  
  publish:
    needs: [test, build]
    name: Publish Project to Nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - name: Publish
      run: dotnet nuget push MonkeyDotNet/Monkey/Monkey.nuspec -k ${APPKEY} -s https://www.nuget.org/api/v2/package
      env:
        APPKEY: ${{ secrets.APPKEY }}
